version: "3.8"
services:
  db:
    image: mysql:8
    container_name: kosa_mysql
    restart: always
    environment:
      MYSQL_DATABASE: kosa_db
      MYSQL_USER: kosa
      MYSQL_PASSWORD: kosa1234
      MYSQL_ROOT_PASSWORD: kosa1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:latest
    container_name: kosa_adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
  backend:
    image: busybox
    command: ["echo", "backend placeholder"]

  frontend:
    image: busybox
    command: ["echo", "frontend placeholder"]

volumes:
  mysqldata:
