version: "3.8"
services:
  db:
    image: mysql:8
    container_name: kosa_mysql
    restart: always
    environment:
      MYSQL_DATABASE: kosa_db
      MYSQL_USER: kosa
      MYSQL_PASSWORD: kosa1234
      MYSQL_ROOT_PASSWORD: kosa1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: kosa_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kosa_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: kosa
      SPRING_DATASOURCE_PASSWORD: kosa1234
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    container_name: kosa_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysqldata:
